---
- hosts: managers
  roles:
    - common
    - cpanel
    - post
  vars:
    destinationDir: "~/myelanman"
    staticDir: "{{ destinationDir }}/static"
    djangoDir: "{{ destinationDir }}/django"
    makefileversion: "0.12"
    short: false
