---
configsections:
    - { id: 'fwport', shortname: 'firewallports', listobject: false, desc: 'Firewall ports actions' }
    - { id: 'fwip', shortname: 'firewallwhiteip', listobject: true, desc: 'Firewall white list for IP' }
    - { id: 'fwproc', shortname: 'csfignorelist', listobject: true, desc: 'process list to ignore' }
    - { id: 'cppro', shortname: 'ea', listobject: false, desc: 'Active EasyApache profile' }
    - { id: 'snmp', shortname: 'serversnmp', listobject: false, desc: 'SNMP Configuration' }
    - { id: 'pftpd', shortname: 'pureftpdlocal', listobject: false, desc: 'pure-ftp local config' }
whmapisections:
    - { id: 'enauth', shortname: 'enable_authentication_provider', desc: 'Enable authentication providers' }
    - { id: 'deauth', shortname: 'disable_authentication_provider', desc: 'Disable authentication providers' }
    - { id: 'enmkt', shortname: 'enable_market_provider', desc: 'Enable cPanel Market provider' }
    - { id: 'demkt', shortname: 'disable_market_provider', desc: 'Disable cPanel Market provider' }
    - { id: 'backupset', shortname: 'backup_config_set', desc: 'configures a servers backup system' }