---
# copy tasks files to relevant roles
  - name: "create roles tasks for {{ rolesapply.shortname }}"
    template:
      src: "{{ rolesapply.shortname }}.yml.j2"
      dest: "{{ destinationDir }}/roles/{{ item.shortname }}/tasks/{{ rolesapply.shortname }}.yml"
    with_items: "{{ roles }}"
    when: item.id == rolesapply.role

