---
  - name: "make sure static directory exists"
    file:
      path: "{{ staticDir }}/"
      state: directory

  - name: "include static portal vars"
    include_vars: "static_portal.yaml"
    
  - name: "create home page"
    template:
      src: "home.html"
      dest: "{{ staticDir }}/index.html"

  - name: "create region files"
    template:
      src: "region.html"
      dest: "{{ staticDir }}/{{ item.shortname }}.html"
    with_items: "{{ regions }}"

  - name: "create role files"
    template:
      src: "role.html"
      dest: "{{ staticDir }}/{{ item.shortname }}.html"
    with_items: "{{ roles }}"

