---
  - name: "make sure static directory exists"
    file:
      path: "{{ staticDir }}/"
      state: directory

  - name: "create region files"
    template:
      src: "region.html"
      dest: "{{ staticDir }}/{{ item.shortname }}.html"
    with_items: "{{ regions }}"
